name: the_umpteenth_logger_hive
description: The Nth Logger with Hive printer
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  ansicolor: ^2.0.2
  flutter: { sdk: flutter }
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  the_umpteenth_logger: { path: ../the_umpteenth_logger }

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
