name: the_umpteenth_logger
description: The Nth Logger
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  ansicolor: ^2.0.2
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
