name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eneskaraosman/action-autotag@master
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
